"""JSON / Markdown / HTML reporting for arb signals and backtest results."""

from __future__ import annotations

import html
import json
from dataclasses import asdict
from datetime import datetime, timezone
from typing import Any

from .backtest import BacktestResult
from .risk import RiskDetectorResult
from .signals import ArbSignal


def signals_as_json(signals: list[ArbSignal], *, indent: int = 2) -> str:
    return json.dumps([asdict(s) for s in signals], indent=indent, default=str)


def risks_as_json(risks: list[RiskDetectorResult], *, indent: int = 2) -> str:
    return json.dumps([asdict(r) for r in risks], indent=indent, default=str)


def backtest_as_json(result: BacktestResult, *, indent: int = 2) -> str:
    payload: dict[str, Any] = {
        "summary": result.to_dict(),
        "trades": [asdict(t) for t in result.trades],
    }
    return json.dumps(payload, indent=indent, default=str)


def signals_as_markdown(signals: list[ArbSignal], *, title: str = "Arb Signals") -> str:
    lines = [f"# {title}", ""]
    if not signals:
        lines.append("_No signals above threshold._")
        return "\n".join(lines)
    for s in signals:
        lines.append(f"## {s.symbol} — {s.high_venue.value} short / {s.low_venue.value} long")
        lines.append("")
        lines.append(f"- **Spread:** {s.spread_bps_per_hour:.2f} bps/h "
                     f"({s.annualized_spread_pct:.1f}% APR)")
        lines.append(f"- **Recommended size:** ${s.recommended_size_usd:,.0f}")
        lines.append(f"- **Breakeven:** {s.breakeven_holding_hours:.1f}h")
        lines.append(f"- **Confidence:** {s.confidence:.2f}")
        lines.append(f"- **Why:** {s.reason}")
        lines.append("")
    return "\n".join(lines)


def backtest_as_markdown(result: BacktestResult, *, title: str = "Backtest") -> str:
    lines = [f"# {title}", ""]
    s = result.to_dict()
    lines.append(f"- **Trades:** {int(s['n_trades'])}")
    lines.append(f"- **Total PnL:** ${s['total_pnl_usd']:,.2f}")
    lines.append(f"- **Win rate:** {s['win_rate']:.1%}")
    lines.append(f"- **Avg PnL %:** {s['avg_pnl_pct']:.3f}%")
    lines.append(f"- **PnL % stdev:** {s['pnl_pct_std']:.3f}%")
    lines.append(f"- **Sharpe proxy:** {s['sharpe_proxy']:.2f}")
    lines.append("")
    if result.trades:
        lines.append("| open | hours | size | funding | basis | fees | total | reason |")
        lines.append("|---:|---:|---:|---:|---:|---:|---:|---|")
        for t in result.trades:
            opened = datetime.fromtimestamp(t.opened_at, tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
            lines.append(
                f"| {opened} | {t.hours_held:.1f} | ${t.entry_size_usd:,.0f} "
                f"| ${t.funding_pnl_usd:,.2f} | ${t.basis_pnl_usd:,.2f} | ${t.fees_usd:,.2f} "
                f"| ${t.total_pnl_usd:,.2f} | {t.reason_close} |"
            )
    return "\n".join(lines)


_HTML_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
:root { --bg:#0a0e1a; --surface:#111827; --text:#e8ecf4; --text2:#8899b4;
        --accent:#3b82f6; --gold:#f59e0b; --red:#ef4444; --green:#22c55e;
        --border:#2a3550; }
* { box-sizing: border-box; }
body { font-family:-apple-system,"Inter",sans-serif; background:var(--bg);
       color:var(--text); margin:0; padding:32px 24px; line-height:1.55; }
.wrap { max-width: 1000px; margin: 0 auto; }
h1 { font-size:1.8rem; margin:0 0 16px; }
.signal,.risk { background:var(--surface); border:1px solid var(--border);
                border-radius:10px; padding:16px 20px; margin-bottom:14px; }
.signal h2 { margin:0 0 8px; font-size:1.1rem; color:var(--accent); }
.badge { display:inline-block; padding:3px 10px; border-radius:6px;
         font-size:0.82rem; font-weight:700; margin-right:8px; }
.badge.gold { background:rgba(245,158,11,0.18); color:var(--gold); }
.badge.green { background:rgba(34,197,94,0.18); color:var(--green); }
.badge.red { background:rgba(239,68,68,0.18); color:var(--red); }
.badge.blue { background:rgba(59,130,246,0.18); color:var(--accent); }
.kv { color:var(--text2); font-size:0.88rem; margin-top:6px; }
table { border-collapse:collapse; margin-top:14px; width:100%; }
th,td { border:1px solid var(--border); padding:6px 10px; text-align:left; }
th { background:rgba(0,0,0,0.18); color:var(--text2); font-weight:600; }
.pnl-pos { color:var(--green); }
.pnl-neg { color:var(--red); }
footer { color:var(--text2); font-size:0.8rem; margin-top:40px; text-align:center; }
</style>
</head>
<body><div class="wrap">
"""

_HTML_TAIL = (
    '<footer>Generated by drift-funding-monitor · MIT · '
    '<a style="color:#3b82f6" href="https://github.com/mkzung/drift-funding-monitor">'
    'github.com/mkzung/drift-funding-monitor</a></footer>'
    "</div></body></html>"
)


def signals_as_html(signals: list[ArbSignal], *, title: str = "Arb Signals") -> str:
    head = _HTML_HEAD.replace("{title}", html.escape(title))
    body = [head, f"<h1>{html.escape(title)}</h1>"]
    if not signals:
        body.append('<p style="color:#8899b4">No signals above threshold.</p>')
    for s in signals:
        body.append('<div class="signal">')
        body.append(
            f'<h2>{html.escape(s.symbol)} — '
            f'<span class="badge red">SHORT {s.high_venue.value}</span>'
            f'<span class="badge green">LONG {s.low_venue.value}</span></h2>'
        )
        body.append(
            f'<div><span class="badge blue">{s.spread_bps_per_hour:.2f} bps/h</span>'
            f'<span class="badge gold">{s.annualized_spread_pct:.1f}% APR</span>'
            f'<span class="badge">confidence {s.confidence:.2f}</span></div>'
        )
        body.append(
            f'<div class="kv">Recommended size: ${s.recommended_size_usd:,.0f} · '
            f'breakeven: {s.breakeven_holding_hours:.1f}h · '
            f'{html.escape(s.reason)}</div>'
        )
        body.append("</div>")
    body.append(_HTML_TAIL)
    return "".join(body)


def backtest_as_html(result: BacktestResult, *, title: str = "Backtest") -> str:
    head = _HTML_HEAD.replace("{title}", html.escape(title))
    s = result.to_dict()
    body = [head, f"<h1>{html.escape(title)}</h1>"]
    body.append('<div class="signal">')
    body.append(
        f'<span class="badge blue">{int(s["n_trades"])} trades</span>'
        f'<span class="badge {"green" if s["total_pnl_usd"] >= 0 else "red"}">'
        f'PnL ${s["total_pnl_usd"]:,.0f}</span>'
        f'<span class="badge gold">win {s["win_rate"]:.0%}</span>'
        f'<span class="badge">Sharpe-proxy {s["sharpe_proxy"]:.2f}</span>'
    )
    body.append(f'<div class="kv">Avg PnL {s["avg_pnl_pct"]:.3f}% · '
                f'σ {s["pnl_pct_std"]:.3f}%</div></div>')
    if result.trades:
        body.append("<table><tr><th>opened</th><th>hours</th><th>size</th>"
                    "<th>funding</th><th>basis</th><th>fees</th>"
                    "<th>total</th><th>close</th></tr>")
        for t in result.trades:
            cls = "pnl-pos" if t.total_pnl_usd >= 0 else "pnl-neg"
            opened = datetime.fromtimestamp(t.opened_at, tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
            body.append(
                f"<tr><td>{opened}</td><td>{t.hours_held:.1f}</td>"
                f"<td>${t.entry_size_usd:,.0f}</td>"
                f"<td>${t.funding_pnl_usd:,.2f}</td>"
                f"<td>${t.basis_pnl_usd:,.2f}</td>"
                f"<td>${t.fees_usd:,.2f}</td>"
                f'<td class="{cls}">${t.total_pnl_usd:,.2f}</td>'
                f"<td>{html.escape(t.reason_close)}</td></tr>"
            )
        body.append("</table>")
    body.append(_HTML_TAIL)
    return "".join(body)
